### ISSUE TITLE
Automatically redirect to `/` on `404``

### ISSUE THREAD

**Issue by BracketJohn** [sidebase/docs#55]
### Describe the feature

We sometimes change the docs-structure, links stop working thne: https://sidebase.io/why

It would be great if we can forward theses 404 pages per default, instead of showing the docus 404 page:
![image](https://user-images.githubusercontent.com/25911230/208296574-3ddf56da-dc83-4fed-8f47-53a1299ade74.png)

**Comment by mario-neuhold** [comment]
i just stumpled upon this broken link on discord: https://sidebase.io/sidebase/getting-started. i would much rather get redirected to the successor of that page (https://sidebase.io/sidebase/welcome), than to `/`.
(this happened  in this commit e72946ebc6984b50ec87f70dea71a43bcc3a1746 btw)

if there is no direct successor, it would be nice to find a useful 404 page rather than a general redirect to `/`:
- point to the nav tree in the sidebar 
- info about the search feature
- a direkt link to `/` of the docs
- "can't find what you are looking for? ask us on discord or open an issue"
